### PR TITLE
Flesh out GetMode documentation

### PR DESCRIPTION
**Pull request by frenchy64**
I don't know the procedure for updating these docs. Are they frozen until Cockos bumps them upstream?

### CODE REVIEW

**Comment by X-Raym** [comment]
these doc are user uploaded, cockos not involved here.

**Comment by X-Raym** [comment]
reascripthelp.html is a direct dump of the generated doc though, it isnt meant to have user addition.

**Comment by frenchy64** [comment]
Yes, I figured. So is there anything you'd recommend to do with such a contribution?

**Comment by X-Raym** [comment]
@frenchy64 the doc by mespotine has manual entries.

https://mespotin.uber.space/Ultraschall/Reaper_Api_Documentation.html

**Pull request closed without merging**
