### PR TITLE
Update State Chunk Definitions

### PR DESCRIPTION
**Pull request by Buy-One**
Added a note

### CODE REVIEW

**Comment by X-Raym** [comment]
@Buy-One if you are on journey to document every chunk and nodes maybe we should let you a bit of time so you can propose a big pull requests in one shot ? 😄 
Thx anyway, it will be handy for those who want to play with the reaper parser and project generator script we are polishing.

**Comment by Buy-One** [comment]
@X-Raym Sorry, didn't see your message until after the fact. I felt i was causing a bit of a trouble with small updates, but i only do so lest i forget. If you don't feel like merging them please don't feel compelled. I guess i can keep updating the file while the pull request is pending and it can be merged after a while, say in a week or so.
Project generator? Didn't hear of that, sounds interesting. Will try to find out more.

**Comment by X-Raym** [comment]
@Buy-One Not too much trouble don't worry :P
What you can do is fork the repo, do your commit on there one by one, and then create a pull request from your repo where we will get all updates in one merge :)

**Comment by Buy-One** [comment]
@X-Raym OK, i will consider doing it as you suggested.

**Comment by X-Raym** [comment]
@Buy-One Anyway, be sure your contributions to doc chunk is much appreciated ! 😃

**Pull request merged**
